version: "3"
services:
  mysql:
    image: mariadb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: sspanel
      MYSQL_USER: ss
      MYSQL_PASSWORD: pass
    ports:
      - 13306:3306/tcp
    volumes:
      - ./mariadb/db.sql:/docker-entrypoint-initdb.d/db.sql

  redis:
    image: redis:3-alpine

  ssr:
    build: shadowsocksr
    network_mode: host
    volumes:
      - ./shadowsocksr/user-config.json:/opt/shadowsocksr-manyuser/user-config.json
      - ./shadowsocksr/userapiconfig.py:/opt/shadowsocksr-manyuser/userapiconfig.py
      - ./shadowsocksr/usermysql.json:/opt/shadowsocksr-manyuser/usermysql.json
    command: -s 0.0.0.0 -m aes-256-cfb -o tls1.2_ticket_auth_compatible -O auth_sha1_v2_compatible
    depends_on:
      - mysql

  php:
    build: ss-panel
    volumes:
      - ssp-volume:/var/www/html
      - ./ss-panel/env.template:/var/www/html/env.template
    command: /bin/sh -c "envsubst '$$BASE_URL' < /var/www/html/env.template > /var/www/html/.env && php-fpm"
    environment:
      BASE_URL: ${BASE_URL}
    links:
      - mysql
      - redis

  nginx:
    image: nginx:1.11.9-alpine
    volumes:
      - ssp-volume:/var/www/html
      - ./nginx/default.template:/etc/nginx/conf.d/default.template
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=_
      - NGINX_PORT=80
    command: /bin/sh -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    links:
      - php


volumes:
  ssp-volume:
